### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by UmairAhmed420** [Chrisvin/LiquidSwipe#3]
when i convert it in ontouchListener swipe and when i swipe more than 4-5 pages it gives this error 
 java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
        at com.example.liquidswipedemo.CustomPagerAdapter.instantiateItem(CustomPagerAdapter.kt:27)
        at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1224)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager$3.run(ViewPager.java:273)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:977)
        at android.view.Choreographer.doCallbacks(Choreographer.java:785)
        at android.view.Choreographer.doFrame(Choreographer.java:714)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:963)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6819)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)

**Comment by Chrisvin** [comment]
When you convert what in `onTouchListener`? 

Could you share the code changes that resulted in the crash?

**Comment by UmairAhmed420** [comment]
i havent used it in my sample projects just execute your project and i convert it from Default to Touch Interactive and when i swipe more than 5 it crash and give mentioned error

**Comment by Chrisvin** [comment]
I'm unable to reproduce the crash. 
Does the [touch interactive demo app](https://github.com/Chrisvin/LiquidSwipe/releases/download/1.3/LiquidSwipeDemo.-.Touch_Interactive.apk) crash as well?
If **yes**, then could you provide your device details?
If **no**, then could it be possible that you might have changed the data values by mistake or made some other change that might have lead to the issue? (Can you kindly try discarding all your changes and uncommenting the [code block containing the touch interactive code](https://github.com/Chrisvin/LiquidSwipe/blob/master/app/src/main/java/com/example/liquidswipedemo/MainActivity.kt#L16)?)

**Comment by Chrisvin** [comment]
Closing due to inactivity, feel free to reopen if the issue persists.
